name: Homexo
favicon: null
layout_spectrum: 0.580012823222205
typography_spectrum: 0.634780059568584
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.9837873026262969
  lightness: 0.726350569864735
  saturation: 0.34090973366983235
  rhythmicContrast: 0.5656541013158858
purpose: []
